### ISSUE TITLE
Is it possible to wait for jobs running against a different ref?

### ISSUE THREAD

**Issue by vezaynk** [yogeshlonkar/wait-for-jobs#34]
I have a repository where a long-running process is triggered on every merge to master. As long as a job is running on master, I want to prevent every other PR from being merged. Is it possible to accomplish with this?

**Comment by yogeshlonkar** [comment]
This actions waits for jobs in same run, what you are looking for is waiting on other runs so this action won't be of any help.

Apart from [status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) I don't think there is way to achieve what you want. Even with it there might be time period when checks are disabled and enabled where someone might merge PR's.

What you can do is enable this on repository settings

> - [ ] Allow rebase merging

This will prevent people from merging before rebasing their HEAD branches. You can also enable

> - [ ] Always suggest updating pull request branches

so on HEAD branch update PR workflows can wait till run from main branch is done and pass the checks
