### ISSUE TITLE
Maximum TTL

### ISSUE THREAD

**Issue by garronej** [yogeshlonkar/wait-for-jobs#80]
Hello,  
Would you be open to a drastical icreace of the maximum TTL from 15min to an hour?  
https://github.com/yogeshlonkar/wait-for-jobs/blob/98618aec434474dcebd1a8e9cd702d3b98b233f4/src/WaitForJobs.ts#L54-L59  

In our usecase, now that we started to building for Apple Sillicon the build time of the docker image we are waiting for have increaced quite a bit and it is very unpredictible, it take in between 26 to 35 minute.  

As a temorary workaround we've done this:  

https://github.com/InseeFrLab/onyxia/blob/cb2ecd83416e51ae95e37f18f4b4835fe72f4047/.github/workflows/ci.yaml#L110-L117  

But this is a hack.  

If you're OK with the idea I can submit a PR. Otherwise I understand the idea of not wanting to enable patern that you consider wastefull in resources, we will just internalize this action.

**Comment by yogeshlonkar** [comment]
I think there problem in you runner or compilation, I Won't be changing this TTL.

If you wish you can folk this repository.

**Comment by yogeshlonkar** [comment]
[v0.3.0](https://github.com/yogeshlonkar/wait-for-jobs/releases/tag/v0.3.0) now allows this behaviour
